---
title: "My Fisheries Analysis"
author: "Matthew Pfaff"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# Attaching libraries

library(tidyverse)
library(here)
library(janitor)
library(paletteer) # install.packages("paletteer")
```

Read in noaa_landings.csv

```{r}
us_landing <- read.csv(here("data/noaa_landings.csv"),
                       na = "no data")

```

Now let's clean up the column names:

```{r}
salmon_clean <- us_landing %>% 
  clean_names() %>% 
  mutate(afs_name = str_to_lower(afs_name)) %>%
  # mutate(dollars_num = parse_number(dollars_usd)) %>%
  filter(str_detect(afs_name, pattern = "salmon")) %>% 
  separate(afs_name, into = c("salmon_group", "subgroup"), sep = ", ") %>% 
  drop_na(dollars_usd)
         
```

### From the book

```{r}
salmon_clean <- us_landing %>% 
  clean_names() %>% # Make column headers snake_case
  mutate(
    afs_name = str_to_lower(afs_name)
  ) %>% # Converts character columns to lowercase
 # mutate(dollars_num = parse_number(dollars_usd)) %>% # Just keep numbers from $ column
  filter(str_detect(afs_name, pattern = "salmon")) %>% # Only keep entries w/"salmon"
  separate(afs_name, into = c("group", "subgroup"), sep = ", ") %>% # Note comma-space
  drop_na(dollars_num) # Drop (listwise deletion) any observations with NA for dollars_num
```


### Annual total value by salmon subgroup

```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup) %>% 
  summarize(
    tot_value = sum(dollars_nom, na.rm = TRUE)
  )
```


### Activity

From `salmon_us_annual`, create a line graph with year on the x-axis and tot_value on the y-axis. Hint: remember groupings!

```{r}
ggplot(data = salmon_us_annual, aes(x = year,
                                    y = total_num,
                                    group = subgroup)) +
  geom_line(aes(color = subgroup)) +
  theme_bw() +
  labs(x = "Year", 
       y = "US commercial salmon value (USD)",
       title = "My awesome graph") +
  scale_color_paletteer_d("calecopal::figmtn")

# calecopal figmtn

```









